blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/orgs/Nekogram/discussions/new?category=q-a
    about: Please ask and answer questions here.
  - name: Official Telegram Channel
    url: https://t.me/nekoupdates
    about: Subscribe for notifications and releases.
